language: go
go:
- 1.12
- 1.13
- 1.14
- master
before_install:
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
script:
- go test -v
- $GOPATH/bin/goveralls -service=travis-ci
