// Code generated by "stringer -type AuthType"; DO NOT EDIT

package hawk

import "fmt"

const _AuthType_name = "HeaderResponseBewit"

var _AuthType_index = [...]uint8{0, 6, 14, 19}

func (i AuthType) String() string {
	if i < 0 || i >= AuthType(len(_AuthType_index)-1) {
		return fmt.Sprintf("AuthType(%d)", i)
	}
	return _AuthType_name[_AuthType_index[i]:_AuthType_index[i+1]]
}
