on: [push, pull_request]
name: Golang Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Grab deps
      run: |
        go get github.com/mattn/goveralls
        go get golang.org/x/tools/cmd/cover
      env:
        GO111MODULE: off
    - name: Grab modules
      run: go get ./...
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test -v -coverprofile=profilecov ./...
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profilecov
        flag-name: Go-${{ matrix.go }}
        parallel: true
  
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
